"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
type Order={id:number;productName:string;quantity:number;price:number;status:string;paymentStatus:string;createdAt:string};
type Customer={id:number;name:string;email:string;phone:string;status:string;emailVerified:boolean;createdAt:string;addressCount:number;orderCount:number;totalSpent:number;orders:Order[]};
const PAGE_SIZE=100;
export default function AdminMusterilerPage(){
const [customers,setCustomers]=useState<Customer[]>([]),[search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState("Tümü");const [selected,setSelected]=useState<number|null>(null),[loading,setLoading]=useState(true),[page,setPage]=useState(1);const router=useRouter();
async function load(){const response=await fetch("/api/admin/musteriler",{cache:"no-store"});if(response.status===401){router.replace("/admin/giris");return;}const data=await response.json();if(data.success)setCustomers(data.customers);setLoading(false);}useEffect(()=>{void load();},[]);
async function changeStatus(id:number,status:string){const response=await fetch("/api/admin/musteriler",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(response.ok)await load();}
const filtered=useMemo(()=>{const value=search.toLocaleLowerCase("tr");return customers.filter(item=>(statusFilter==="Tümü"||item.status===statusFilter)&&`${item.id} ${item.name} ${item.email} ${item.phone}`.toLocaleLowerCase("tr").includes(value));},[customers,search,statusFilter]);
useEffect(()=>{setPage(1);},[search,statusFilter]);
const pageCount=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);const totals={customers:customers.length,verified:customers.filter(item=>item.emailVerified).length,active:customers.filter(item=>item.status==="Aktif").length,orders:customers.reduce((sum,item)=>sum+item.orderCount,0),revenue:customers.reduce((sum,item)=>sum+item.totalSpent,0)};
if(loading)return <main className="min-h-screen bg-slate-100 p-10 text-center font-black text-slate-900">Müşteriler yükleniyor...</main>;
return <main className="min-h-screen bg-slate-100 p-3 text-slate-950 sm:p-5"><div className="mx-auto max-w-[1800px]">
<header className="flex flex-wrap items-center justify-between gap-4 rounded-xl bg-slate-900 px-5 py-4 text-white"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-amber-300">FlorioTR Yönetim</p><h1 className="text-2xl font-black">Müşteri Tablosu</h1></div><div className="flex flex-wrap gap-4 text-xs font-bold"><span>Toplam <b className="text-lg">{totals.customers}</b></span><span>Doğrulanmış <b className="text-lg">{totals.verified}</b></span><span>Aktif <b className="text-lg">{totals.active}</b></span><span>Sipariş <b className="text-lg">{totals.orders}</b></span><span>Harcama <b className="text-lg">{totals.revenue.toLocaleString("tr-TR")} TL</b></span></div></header>
<div className="mt-3 grid gap-2 rounded-lg border bg-white p-2 shadow-sm md:grid-cols-[1fr_160px_auto]"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="ID, ad, e-posta veya telefon ara..." className="h-10 rounded-md border px-3 text-sm"/><select value={statusFilter} onChange={event=>setStatusFilter(event.target.value)} className="h-10 rounded-md border px-3 text-sm font-bold"><option>Tümü</option><option>Aktif</option><option>Pasif</option></select><div className="flex items-center justify-end gap-2 px-2 text-xs font-black text-slate-600">{filtered.length} kayıt · Sayfa {page}/{pageCount}</div></div>
<div className="mt-3 overflow-auto rounded-lg border border-slate-300 bg-white shadow-sm"><table className="w-full min-w-[1150px] border-collapse text-[12px]"><thead className="sticky top-0 z-10 bg-slate-800 text-left text-white"><tr>{["ID","Ad Soyad","E-posta","Telefon","Kayıt","Doğrulama","Durum","Adres","Sipariş","Harcama","İşlem"].map(title=><th key={title} className="border-r border-slate-600 px-2 py-2 font-black">{title}</th>)}</tr></thead><tbody>{visible.map((customer,index)=><tr key={customer.id} onClick={()=>setSelected(selected===customer.id?null:customer.id)} className={`cursor-pointer border-b hover:bg-blue-50 ${index%2?"bg-slate-50":"bg-white"}`}><td className="px-2 py-1.5 font-black">{customer.id}</td><td className="max-w-[180px] truncate px-2 py-1.5 font-bold">{customer.name}</td><td className="max-w-[240px] truncate px-2 py-1.5">{customer.email}</td><td className="whitespace-nowrap px-2 py-1.5">{customer.phone}</td><td className="whitespace-nowrap px-2 py-1.5">{new Date(customer.createdAt).toLocaleDateString("tr-TR")}</td><td className={`px-2 py-1.5 font-black ${customer.emailVerified?"text-emerald-700":"text-amber-700"}`}>{customer.emailVerified?"Doğrulandı":"Bekliyor"}</td><td className={`px-2 py-1.5 font-black ${customer.status==="Aktif"?"text-blue-700":"text-red-700"}`}>{customer.status}</td><td className="px-2 py-1.5 text-center">{customer.addressCount}</td><td className="px-2 py-1.5 text-center font-black">{customer.orderCount}</td><td className="whitespace-nowrap px-2 py-1.5 font-black">{customer.totalSpent.toLocaleString("tr-TR")} TL</td><td className="px-2 py-1.5"><button onClick={event=>{event.stopPropagation();void changeStatus(customer.id,customer.status==="Aktif"?"Pasif":"Aktif")}} className={`rounded px-2 py-1 text-[10px] font-black text-white ${customer.status==="Aktif"?"bg-red-600":"bg-emerald-700"}`}>{customer.status==="Aktif"?"Pasifleştir":"Aktifleştir"}</button></td></tr>)}</tbody></table>{!visible.length&&<div className="p-10 text-center font-bold">Kayıt bulunamadı.</div>}</div>
<div className="mt-3 flex items-center justify-between"><p className="text-xs font-bold text-slate-600">Sayfa başına 100 müşteri</p><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(current=>current-1)} className="rounded-md border bg-white px-4 py-2 text-xs font-black disabled:opacity-40">← Önceki</button><button disabled={page>=pageCount} onClick={()=>setPage(current=>current+1)} className="rounded-md border bg-white px-4 py-2 text-xs font-black disabled:opacity-40">Sonraki →</button></div></div>
{selected&&(()=>{const customer=customers.find(item=>item.id===selected);if(!customer)return null;return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onClick={()=>setSelected(null)}><div className="max-h-[85vh] w-full max-w-4xl overflow-auto rounded-2xl bg-white p-5 shadow-2xl" onClick={event=>event.stopPropagation()}><div className="flex justify-between gap-4"><div><p className="text-xs font-black text-slate-500">MÜŞTERİ #{customer.id}</p><h2 className="text-xl font-black">{customer.name}</h2><p className="text-sm text-slate-600">{customer.email} · {customer.phone}</p></div><button onClick={()=>setSelected(null)} className="h-9 w-9 rounded-full bg-slate-100 font-black">✕</button></div><h3 className="mt-5 font-black">Sipariş Geçmişi ({customer.orderCount})</h3><div className="mt-2 overflow-hidden rounded-lg border"><table className="w-full text-xs"><tbody>{customer.orders.map(order=><tr key={order.id} className="border-b"><td className="p-2 font-black">#{order.id}</td><td className="p-2">{order.productName}</td><td className="p-2">{new Date(order.createdAt).toLocaleDateString("tr-TR")}</td><td className="p-2 font-bold">{order.status}</td><td className="p-2 font-black">{order.price*order.quantity} TL</td></tr>)}</tbody></table>{!customer.orders.length&&<p className="p-5 text-center text-slate-500">Henüz sipariş yok.</p>}</div></div></div>})()}
</div></main>;
}
