"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
type Shop={id:number;shopName:string;owner:string;phone:string;email:string;city:string;district:string;address:string;status:string;contactStatus:string;adminNote:string|null;createdAt:string};
const applicationStatuses=["Tümü","Onay Bekliyor","Onaylandı","Reddedildi"];
const contactStatuses=["Aranacak","Görüşüldü","Uygun","Uygun Değil"];
export default function AdminCicekcilerPage(){
const [shops,setShops]=useState<Shop[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[filter,setFilter]=useState("Tümü"),[selected,setSelected]=useState<number|null>(null),[note,setNote]=useState("");const [message,setMessage]=useState<Record<number,string>>({});const router=useRouter();
async function load(){const response=await fetch("/api/admin/cicekci",{cache:"no-store"});if(response.status===401){router.replace("/admin/giris");return;}const data=await response.json();if(data.success)setShops(data.flowerShops);setLoading(false);}useEffect(()=>{void load();},[]);
async function update(id:number,changes:Record<string,unknown>){setMessage(current=>({...current,[id]:"Kaydediliyor..."}));const response=await fetch("/api/admin/cicekci",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...changes})});const data=await response.json();setMessage(current=>({...current,[id]:data.success?(data.notificationSent?"Kaydedildi, e-posta gönderildi.":"Kaydedildi."):(data.message||"Kaydedilemedi.")}));if(data.success)await load();}
const filtered=useMemo(()=>{const query=search.toLocaleLowerCase("tr");return shops.filter(shop=>(filter==="Tümü"||shop.status===filter)&&`${shop.id} ${shop.shopName} ${shop.owner} ${shop.phone} ${shop.email} ${shop.city} ${shop.district}`.toLocaleLowerCase("tr").includes(query));},[shops,search,filter]);
if(loading)return <main className="min-h-screen bg-slate-100 p-10 text-center font-black">Çiçekçiler yükleniyor...</main>;
return <main className="min-h-screen bg-slate-100 p-3 text-slate-950 sm:p-5"><div className="mx-auto max-w-[1800px]"><header className="flex flex-wrap items-center justify-between gap-4 rounded-xl bg-slate-900 px-5 py-4 text-white"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-amber-300">FlorioTR Yönetim</p><h1 className="text-2xl font-black">Çiçekçi Başvuruları</h1></div><div className="flex gap-5 text-xs font-bold"><span>Toplam <b className="text-lg">{shops.length}</b></span><span>Bekleyen <b className="text-lg text-amber-300">{shops.filter(shop=>shop.status==="Onay Bekliyor").length}</b></span><span>Onaylı <b className="text-lg text-emerald-300">{shops.filter(shop=>shop.status==="Onaylandı").length}</b></span><span>Aranacak <b className="text-lg text-blue-300">{shops.filter(shop=>shop.contactStatus==="Aranacak").length}</b></span></div></header>
<div className="mt-3 grid gap-2 rounded-lg border bg-white p-2 shadow-sm md:grid-cols-[1fr_190px_auto]"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Mağaza, yetkili, telefon, e-posta veya konum ara..." className="h-10 rounded-md border px-3 text-sm"/><select value={filter} onChange={event=>setFilter(event.target.value)} className="h-10 rounded-md border px-3 text-sm font-bold">{applicationStatuses.map(item=><option key={item}>{item}</option>)}</select><p className="self-center px-3 text-xs font-black text-slate-600">{filtered.length} kayıt</p></div>
<div className="mt-3 overflow-auto rounded-lg border border-slate-300 bg-white shadow-sm"><table className="w-full min-w-[1250px] border-collapse text-[12px]"><thead className="sticky top-0 z-10 bg-slate-800 text-left text-white"><tr>{["ID","Mağaza","Yetkili","Telefon","E-posta","Konum","Başvuru","Görüşme","Başvuru Durumu","Detay"].map(title=><th key={title} className="border-r border-slate-600 px-2 py-2 font-black">{title}</th>)}</tr></thead><tbody>{filtered.map((shop,index)=><tr key={shop.id} className={`border-b ${index%2?"bg-slate-50":"bg-white"}`}><td className="px-2 py-1.5 font-black">{shop.id}</td><td className="max-w-[180px] truncate px-2 py-1.5 font-black">{shop.shopName}</td><td className="max-w-[150px] truncate px-2 py-1.5">{shop.owner}</td><td className="whitespace-nowrap px-2 py-1.5">{shop.phone}</td><td className="max-w-[220px] truncate px-2 py-1.5">{shop.email}</td><td className="whitespace-nowrap px-2 py-1.5">{shop.district} / {shop.city}</td><td className="whitespace-nowrap px-2 py-1.5">{new Date(shop.createdAt).toLocaleDateString("tr-TR")}</td><td className="px-2 py-1"><select value={shop.contactStatus||"Aranacak"} onChange={event=>void update(shop.id,{contactStatus:event.target.value})} className="w-full rounded border px-2 py-1 font-bold">{contactStatuses.map(item=><option key={item}>{item}</option>)}</select></td><td className="px-2 py-1"><select value={shop.status} onChange={event=>void update(shop.id,{status:event.target.value})} className={`w-full rounded border px-2 py-1 font-black ${shop.status==="Onaylandı"?"text-emerald-700":shop.status==="Reddedildi"?"text-red-700":"text-amber-700"}`}>{applicationStatuses.slice(1).map(item=><option key={item}>{item}</option>)}</select></td><td className="px-2 py-1"><button onClick={()=>{setSelected(shop.id);setNote(shop.adminNote||"")}} className="rounded bg-slate-800 px-3 py-1 font-black text-white">Aç</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center font-bold">Başvuru bulunamadı.</p>}</div>
{selected&&(()=>{const shop=shops.find(item=>item.id===selected);if(!shop)return null;return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onClick={()=>setSelected(null)}><div className="w-full max-w-2xl rounded-2xl bg-white p-5 shadow-2xl" onClick={event=>event.stopPropagation()}><div className="flex justify-between gap-4"><div><p className="text-xs font-black text-slate-500">ÇİÇEKÇİ #{shop.id}</p><h2 className="text-2xl font-black">{shop.shopName}</h2><p className="text-sm font-bold text-slate-600">{shop.owner} · {shop.phone}</p></div><button onClick={()=>setSelected(null)} className="h-9 w-9 rounded-full bg-slate-100 font-black">✕</button></div><div className="mt-4 grid gap-3 rounded-xl bg-slate-100 p-4 text-sm sm:grid-cols-2"><p><b>E-posta:</b><br/>{shop.email}</p><p><b>Konum:</b><br/>{shop.district} / {shop.city}</p><p className="sm:col-span-2"><b>Adres:</b><br/>{shop.address}</p></div><label className="mt-4 block text-sm font-black">Yönetici görüşme notu<textarea value={note} onChange={event=>setNote(event.target.value)} rows={5} placeholder="Görüşme tarihi, üretim kapasitesi, teslimat bölgesi, özel notlar..." className="mt-2 w-full rounded-xl border p-3 font-medium"/></label>{message[shop.id]&&<p className="mt-3 rounded-lg bg-emerald-50 p-2 text-center text-xs font-black text-emerald-800">{message[shop.id]}</p>}<button onClick={()=>void update(shop.id,{adminNote:note})} className="mt-4 w-full rounded-xl bg-slate-900 p-3 font-black text-white">Notu Kaydet</button></div></div>})()}
</div></main>;
}
